Repository pixi-viewport/pixi-viewport, pull requests merged in 2024-11, with the labels that each got.

#463 Use viewport parent's local coordinate system rather than global
  src/plugins/Drag.ts
  src/plugins/Pinch.ts
  src/plugins/Wheel.ts
Labels: bug, v6

#420 renamed PixiVieport -> PixiViewport
  src/global.d.ts
Labels: v6

#501 V6
  README.md
  package-lock.json
  package.json
  src/InputManager.ts
  src/PluginManager.ts
  src/Viewport.ts
  src/ease.ts
  src/global.d.ts
  src/index.ts
  src/plugins/Animate.ts
  src/plugins/Bounce.ts
  src/plugins/Clamp.ts
  src/plugins/ClampZoom.ts
  src/plugins/Decelerate.ts
  src/plugins/Drag.ts
  src/plugins/MouseEdges.ts
  src/plugins/Pinch.ts
  src/plugins/Snap.ts
  src/plugins/SnapZoom.ts
  src/plugins/Wheel.ts
  yarn.lock
Labels: enhancement, documentation, v6

#505 fix: update types to match pixi v8
  package.json
  src/global.d.ts
Labels: more-pixi

#509 fix: copy dts files enabled to copy global types file
  .husky/pre-commit
  package.json
  tsconfig.json
  vite.build.ts
Labels: bug
